name: run-regression-tests

on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        targetPlatform: [ 1Q2023 ]
        include:
        - runtime: linux
          os: ubuntu-latest

        - runtime: mac
          os: macOS-latest

        - runtime: windows
          os: windows-latest

    name: Build Plugin
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the eclipse plugin repository.
      - name: 'Setup: Checkout plugin'
        uses: actions/checkout@v2

      # Install the required software.
      - name: 'Setup: Install required software' 
        run: bash ./tests/resources/ci/scripts/setup.sh
        
      # Build the plugin.
      - name: 'Build: Build-Package-RunTests'
        run: bash ./tests/resources/ci/scripts/exec.sh ${{ matrix.targetPlatform }}
